### new-game
POST http://127.0.0.1:8000/new-game
Content-Type: application/json

[
  {
    "name": "aaa"
  },
  {
    "name": "bbb"
  }
]

### start
GET http://127.0.0.1:8000/start
Content-Type: application/json

### move
GET http://127.0.0.1:8000/move?index=2
Content-Type: application/json

### status
GET http://127.0.0.1:8000/status
Content-Type: application/json
